name: recover
description: flutter lib for key recovery
version: 0.0.1
homepage: https://mytiki.com
repository: https://github.com/tiki/recover
issue_tracker: https://github.com/tiki/recover/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^8.3.0
  barcode_scan2: ^4.2.0
  lottie: ^1.2.1
  logging: ^1.0.2
  provider: ^6.0.2
  flutter_secure_storage: ^5.0.2
  wallet:
    git:
      url: https://github.com/tiki/wallet
      ref: 0.0.6
  httpp:
    git:
      url: https://github.com/tiki/httpp
      ref: 0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/recover/res/images/pineapple-pizza.png
    - packages/recover/res/images/avocado.png
    - packages/recover/res/animation/creating.json
  fonts:
    - family: RecoverIcons
      fonts:
        - asset: packages/recover/res/fonts/RecoverIcons.ttf